name: StackHawk Hourly Security Scans

on:
  schedule:
    # Run every hour at minute 0 (e.g., 9:00, 10:00, 11:00, etc.)
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  stackhawk-bulk-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2 hours timeout for all scans
    
    steps:
    - name: 🔍 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🦅 Install StackHawk CLI
      run: |
        # Try multiple installation methods for StackHawk CLI
        echo "Installing StackHawk CLI..."
        
        # Method 1: Try the official installer script
        if curl -sSL https://download.stackhawk.com/hawk/install.sh | bash; then
          echo "✅ StackHawk CLI installed via install script"
          hawk version
        # Method 2: Try direct download with different URL
        elif curl -L "https://github.com/stackhawk/stackhawk-cli/releases/latest/download/hawk-linux.zip" -o hawk.zip && \
             unzip hawk.zip && \
             sudo mv hawk /usr/local/bin/ && \
             rm hawk.zip; then
          echo "✅ StackHawk CLI installed via GitHub releases"
          hawk version
        # Method 3: Use npm if available
        elif command -v npm &> /dev/null && npm install -g @stackhawk/cli; then
          echo "✅ StackHawk CLI installed via npm"
          hawk version
        else
          echo "❌ Failed to install StackHawk CLI"
          echo "Available alternatives:"
          echo "1. Install locally: npm install -g @stackhawk/cli"
          echo "2. Use Docker: docker run --rm stackhawk/hawkscan"
          echo "3. Manual download from: https://docs.stackhawk.com/hawkscan/installation/"
          exit 1
        fi
        
    - name:  Run bulk security scans
      env:
        HAWK_API_KEY: ${{ secrets.HAWK_API_KEY }}
      run: |
        echo "🦅 Starting StackHawk bulk security scans..."
        chmod +x ./bulk-scan-runner.sh
        ./bulk-scan-runner.sh
        
    - name: 📊 Upload scan results
      uses: actions/upload-artifact@v4
      if: always()  # Upload results even if scans fail
      with:
        name: stackhawk-scan-results-${{ github.run_number }}
        path: bulk-scan-results-*.log
        retention-days: 30
